language: node_js
node_js:
  - '8'

cache: yarn

install:
  - yarn global add lerna jest
  - lerna bootstrap

script:
  - yarn install
  - yarn lerna link convert
  - yarn test
  - yarn build

after_success:
  - yarn cov:send

before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
deploy:
  provider: script
  script: 'yarn publish:changed'
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
